apiVersion: v1
kind: Namespace
metadata:
  name: aks-store
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: aks-store
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: aks-store
  namespace: aks-store
spec:
  promotionPolicies:
    - stageSelector:
        name: frontend-dev
      autoPromotionEnabled: true
    - stageSelector:
        name: frontend-test
      autoPromotionEnabled: false
    - stageSelector:
        name: frontend-prod
      autoPromotionEnabled: false
    - stageSelector:
        name: backend-dev
      autoPromotionEnabled: true
    - stageSelector:
        name: backend-test
      autoPromotionEnabled: false
    - stageSelector:
        name: backend-prod
      autoPromotionEnabled: false
