apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: aks-store
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend
      sources:
        direct: true
        autoPromotionOptions:
          selectionPolicy: NewestFreight
    - origin:
        kind: Warehouse
        name: backend-bundle
      sources:
        direct: true
        autoPromotionOptions:
          selectionPolicy: NewestFreight
  promotionTemplate:
    spec:
      vars:
        - name: targetEnv
          value: dev
        - name: argocdApp
          value: aks-store-dev
      steps:
        - task:
            name: promote-frontend
          as: promote-frontend
        - task:
            name: promote-backend-bundle
          as: promote-backend-bundle
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: aks-store
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend
      sources:
        stages:
          - dev
    - origin:
        kind: Warehouse
        name: backend-bundle
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      vars:
        - name: targetEnv
          value: test
        - name: argocdApp
          value: aks-store-test
      steps:
        - task:
            name: promote-frontend
          as: promote-frontend
        - task:
            name: promote-backend-bundle
          as: promote-backend-bundle
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: aks-store
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend
      sources:
        stages:
          - test
    - origin:
        kind: Warehouse
        name: backend-bundle
      sources:
        stages:
          - test
  promotionTemplate:
    spec:
      vars:
        - name: targetEnv
          value: prod
        - name: argocdApp
          value: aks-store-prod
      steps:
        - task:
            name: promote-frontend
          as: promote-frontend
        - task:
            name: promote-backend-bundle
          as: promote-backend-bundle
