apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: frontend-dev
  namespace: aks-store
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend
      sources:
        direct: true
        autoPromotionOptions:
          selectionPolicy: NewestFreight
  promotionTemplate:
    spec:
      vars:
        - name: targetEnv
          value: dev
        - name: argocdApp
          value: aks-store-dev
      steps:
        - task:
            name: promote-frontend
          as: promote-frontend
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: frontend-test
  namespace: aks-store
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend
      sources:
        stages:
          - frontend-dev
  promotionTemplate:
    spec:
      vars:
        - name: targetEnv
          value: test
        - name: argocdApp
          value: aks-store-test
      steps:
        - task:
            name: promote-frontend
          as: promote-frontend
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: frontend-prod
  namespace: aks-store
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend
      sources:
        stages:
          - frontend-test
  promotionTemplate:
    spec:
      vars:
        - name: targetEnv
          value: prod
        - name: argocdApp
          value: aks-store-prod
      steps:
        - task:
            name: promote-frontend
          as: promote-frontend
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: backend-dev
  namespace: aks-store
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: backend-bundle
      sources:
        direct: true
        autoPromotionOptions:
          selectionPolicy: NewestFreight
  promotionTemplate:
    spec:
      vars:
        - name: targetEnv
          value: dev
        - name: argocdApp
          value: aks-store-dev
      steps:
        - task:
            name: promote-backend-bundle
          as: promote-backend-bundle
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: backend-test
  namespace: aks-store
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: backend-bundle
      sources:
        stages:
          - backend-dev
  promotionTemplate:
    spec:
      vars:
        - name: targetEnv
          value: test
        - name: argocdApp
          value: aks-store-test
      steps:
        - task:
            name: promote-backend-bundle
          as: promote-backend-bundle
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: backend-prod
  namespace: aks-store
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: backend-bundle
      sources:
        stages:
          - backend-test
  promotionTemplate:
    spec:
      vars:
        - name: targetEnv
          value: prod
        - name: argocdApp
          value: aks-store-prod
      steps:
        - task:
            name: promote-backend-bundle
          as: promote-backend-bundle
