apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: aks-store-health-gate
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: aks-store-health-gate
  namespace: aks-store-health-gate
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: false
    - stageSelector:
        name: test
      autoPromotionEnabled: false
    - stageSelector:
        name: prod
      autoPromotionEnabled: false
