apiVersion: demo.kargo.io/v1alpha1
kind: ReleaseManifest
metadata:
  name: aks-store-mixed-001
spec:
  application: aks-store
  releaseId: aks-store-mixed-001
  components:
    storeFront:
      repository: ghcr.io/chriskealerant/kargo-demo-store-front
      tag: v1.0.0
    productService:
      repository: ghcr.io/chriskealerant/kargo-demo-product-service
      tag: v1.0.0
    orderService:
      repository: ghcr.io/chriskealerant/kargo-demo-order-service
      tag: v1.0.0
