apiVersion: v1
kind: Service
metadata:
  name: {{ include "aks-store.fullname" . }}-store-front
  labels:
    {{- include "aks-store.labels" . | nindent 4 }}
    app.kubernetes.io/component: store-front
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "aks-store.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: store-front
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aks-store.fullname" . }}-product-service
  labels:
    {{- include "aks-store.labels" . | nindent 4 }}
    app.kubernetes.io/component: product-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "aks-store.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: product-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aks-store.fullname" . }}-order-service
  labels:
    {{- include "aks-store.labels" . | nindent 4 }}
    app.kubernetes.io/component: order-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "aks-store.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: order-service
